export const data = {
  profile: {
    name: "Shreeram Kushwaha",
    username: "shreeramk",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Shreeram",
    bio: "Director of Engineering @UptimeAI\nPython, Angular, Javascript, NodeJS, MongoDB, Influx DB, TimescaleDB, Streamsets, Kafka, AWS, Azure, HTML5, CSS",
    location: "Bangalore, India",
    email: "kushwaha.shreeram@gmail.com",
    website: "http://shreeramk.com",
    linkedin: "in/shreeramkushwaha",
    twitter: "@pom_fret",
    company: "UptimeAI",
    followers: 12,
    following: 3,
  },
  achievements: [
    {
      name: "Starstruck",
      description: "Created a repository that has 16 stars",
      icon: "⭐",
      tier: "Bronze",
    },
    {
      name: "Pull Shark",
      description: "Opened a pull request that has been merged",
      icon: "🦈",
      tier: "x2",
    },
    {
      name: "Arctic Code Vault Contributor",
      description: "Contributed code to the 2020 GitHub Archive Program",
      icon: "🏔️",
      tier: "2020",
    },
  ],
  repositories: [
    {
      name: "Complete-Python-3-Bootcamp",
      visibility: "Public",
      forkedFrom: "Pierian-Data/Complete-Python-3-Bootcamp",
      description: "Course Files for Complete Python 3 Bootcamp Course on Udemy",
      language: "Jupyter Notebook",
      languageColor: "#DA5B0B",
      stars: 0,
      forks: 0,
      url: "https://youtu.be/9p4ETlR5444",
    },
    {
      name: "flutter_login_ui",
      visibility: "Public",
      forkedFrom: "ManuMkumar/flutter_login_ui",
      description: "Course Files for Complete Python 3 Bootcamp Course on Udemy",
      language: "Dart",
      languageColor: "#00B4AB",
      stars: 0,
      forks: 0,
      url: "https://youtu.be/9p4ETlR5444",
    },
    {
      name: "gitignore",
      visibility: "Public",
      forkedFrom: "github/gitignore",
      description: "A collection of useful .gitignore templates",
      language: "Jupyter Notebook",
      languageColor: "#DA5B0B",
      stars: 0,
      forks: 0,
      url: "https://youtu.be/9p4ETlR5444",
    },
    {
      name: "node-opcua-logger",
      visibility: "Public",
      forkedFrom: "cimany/node-opcua-logger",
      description: "An OPCUA Client for logging data to InfluxDB!! 🔥📊",
      language: "JavaScript",
      languageColor: "#f1e05a",
      stars: 0,
      forks: 0,
      url: "https://youtu.be/9p4ETlR5444",
    },
    {
      name: "kafka6",
      visibility: "Public",
      forkedFrom: "tu1ly/kafka6",
      description: "A modern Apache Kafka client for nodejs",
      language: "JavaScript",
      languageColor: "#f1e05a",
      stars: 0,
      forks: 0,
      url: "https://youtu.be/9p4ETlR5444",
    },
    {
      name: "node-opcua-1",
      visibility: "Public",
      forkedFrom: "node-opcua/node-opcua",
      description: "an implementation of a OPC UA stack fully written in javascript and nodejs",
      language: "TypeScript",
      languageColor: "#3178c6",
      stars: 0,
      forks: 0,
      url: "http://node-opcua.github.io/api_doc/",
    },
  ],
  activityOverview: {
    commits: 70,
    pullRequests: 21,
    issues: 0,
    codeReview: 0,
  },
  contributionStats: {
    totalContributions: 2020,
    currentYear: 2026,
    lastYear: 2025,
  },
  recentActivity: {
    period: "February 2026",
    hasActivity: false,
    message: "shreeramk has no activity yet for this period.",
  },
};
